matrix:
  include:
  - language: bash
    name: Shellcheck [Bash running on Ubuntu Bionic 18.04]
    dist: bionic
    before_install:
    - mkdir travis
    - git clone https://github.com/TravisToolbox/shellcheck-travis.git travis/shellcheck
    install:
    - "./travis/shellcheck/install.sh"
    script:
    - "./travis/shellcheck/scan.sh"
  - language: ruby
    name: Link Checking (rvm 2.6)
    rvm: 2.6
    env:
    - WHITELIST="https://github.com/TGWolf"
    - EXCLUDE_FILES="CHANGELOG.md"
    before_install:
    - mkdir travis
    - git clone https://github.com/TravisToolbox/awesomebot-travis.git travis/awesomebot
    install:
    - "./travis/awesomebot/install.sh"
    script:
    - "./travis/awesomebot/scan.sh"
notifications:
  email: false
  slack:
    secure: R+aGjsGyODK7A7CkKQmf0OoSA2j9ek6mnu48+zpN/rs0ruBRlWG45QnVtqj7s6/focpVeIgJeLSolMwFf++NuLuOE8VGYc9JwckEt5Au8aTNdPdKAuXzR1oVtCEblliY6dEAFdDD9tWxd/mi7gqmr4ckI1nveGkZPslkW8S65F7BUXJ8+jY6aVgn6wkwsel3WvfC2oRCqAV8F5TzvcaWd3jpJcxbSouzjjDh0whxZQUbW79TLhb0YS+1b5vyFzo+Vciw2h+113lMIDSOrPmQAr4tsMub8ZZfrjEiqeFlF7CXS5k1c4S/t+/QB3wsVbnVzzY9/gZofmfThThBKBKfjaP2TFqVSVfWh9ztWvDXEs/84kwkz+rYpWz/I2KtSUbMTcCfPCMfR/0bGZaLVgFuhccA03MAfZUhVNLpRkGK9FiFyaJ0uX1uKhZ+1axEPpuwFIUb/3lgSMT3frEK6YL/8QcWJRZR1kkZMNh5qES2gusuiHTAQRDEx/uH8o7oKfvsAQAOljFaccxjBe0HuZbd74ZMmNK6It6GgmTL9ka85bKxgi6JZBlxHV0YdFukbfQwE9dAkYXoGmZ4ySxkye0ISxaVFZk45vLx0+a8kEmgoLT6dTp7I9DEFQ3E+c8/C76uKeVZWC6npUqLdeKhw6jDTzTqeThSjGeOkLJoeWS8YVg=
